import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Sign } from "crypto";
import Logout from "./components/logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex item-center gap-4">
          <Link href={"/"}>HOME</Link>
          <Link href={"/dashboard"}>Dashboard</Link>
          <Link href={"/signin"}>SignIn</Link>
          <Link href={"/signup"}>SignUp</Link>
          <Logout />
        </nav>
        {children}
      </body>
    </html>
  );
}

// end code
